version: '3.7'

services:
    minecraft:
        image: naviodev/pandaspigot:latest
        container_name: minecraft
        stdin_open: true
        tty: true
        restart: unless-stopped
        environment:
            EULA: "true"
        ports:
            - 25565:25565
        volumes:
            - pandaspigot:/data

volumes:
    pandaspigot: {}
